---
apiVersion: v1
kind: Deployment
metadata:
  name: postgres
  namespace: "{{ project_name }}"
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRESQL_DATABASE
              value: pulp
            - name: POSTGRESQL_USER
              value: "{{ database_connection.username }}"
            - name: POSTGRESQL_PASSWORD
              value: "{{ database_connection.password }}"
{% if database_connection.admin_password %}
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: "{{ database_connection.admin_password }}"
{% endif %}
          volumeMounts:
            - readOnly: false
              mountPath: /var/lib/pgsql/data
              name: postgres-data
          image: docker.io/centos/postgresql-96-centos7:9.6
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
