---

- name: Delete any existing management pod
  k8s:
    name: "{{ ansible_operator_meta.name }}-backup-manager"
    kind: Pod
    namespace: "{{ backup_pvc_namespace }}"
    state: absent
    force: true

- name: Remove ownerReferences from admin password secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ admin_password_name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
  no_log: true
  when:
    - admin_password_name is defined
    - admin_password_name | length

- name: Remove ownerReferences from db secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ db_secret_name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
  no_log: true
  when:
    - db_secret_name is defined
    - db_secret_name | length

- name: Remove ownerReferences from storage secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ storage_secret }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
  no_log: true
  when:
    - storage_secret is defined
    - storage_secret | length

- name: Remove ownerReferences from DB fields encryption secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ db_fields_encryption_secret }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
  no_log: true
  when:
    - db_fields_encryption_secret is defined
    - db_fields_encryption_secret | length

- name: Remove ownerReferences from galaxy signing secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ signing_secret }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
  no_log: true
  when:
    - signing_secret is defined
    - signing_secret | length

- name: Remove ownerReferences from container token secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ container_token_secret }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
  no_log: true
  when:
    - container_token_secret is defined
    - container_token_secret | length

- name: Remove ownerReferences from sso secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ sso_secret }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
  no_log: true
  when:
    - sso_secret is defined
    - sso_secret | length
