---

- name: Obtain custom resource information
  set_fact:
    custom_resource: "{{ hostvars[inventory_hostname][custom_resource_key] }}"
    custom_resource_status: "{{ hostvars[inventory_hostname][custom_resource_key]['status'] }}"

- block:
    - include_tasks: init.yml

    - include_tasks: secrets.yml

    - include_tasks: deploy_pulp.yml

    - include_tasks: postgres.yml

    - include_tasks: storage.yml
      when: storage_type | lower == 'file'

    - name: Set flag signifying this restore was successful
      set_fact:
        restore_complete: True

    - include_tasks: cleanup.yml

  when:
    - custom_resource_status['restoreComplete'] is not defined

- name: Update status variables
  include_tasks: update_status.yml
