---

- name: Get secret definition from pvc
  k8s_exec:
    namespace: "{{ backup_pvc_namespace  }}"
    pod: "{{ meta.name }}-backup-manager"
    command: >-
      bash -c "cat '{{ backup_dir }}/secrets.yaml'"
  register: secrets
  no_log: true

- name: Create temp vars file
  tempfile:
    prefix: secret_vars-
  register: secret_vars

- name: Write vars to file locally
  copy:
    dest: "{{ secret_vars.path }}"
    content: "{{ secrets.stdout }}"
    mode: 0640
  no_log: true

- name: Include secret vars from backup
  include_vars: "{{ secret_vars.path }}"
  no_log: true

- name: Apply admin password secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'admin-password.secret.yaml.j2') }}"
  no_log: true

- name: Apply database configuration secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'postgres.secret.yaml.j2') }}"
  no_log: true
  when:
    - db_secret_name is defined
    - db_secret_name | length
    - database_password is defined

- name: Set name of objectstorage file name
  set_fact:
    objstorage_file: 'objectstorage_secret.yaml'

- name: Check to if objectstorage secret exists in  backup directory on PVC
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ meta.name }}-backup-manager"
    command: >-
      bash -c "stat {{ backup_dir }}/{{ objstorage_file }}"
  register: stat_backup_objectstorage

- name: Create object storage secret
  block:
    - name: Get secret definition from pvc
      k8s_exec:
        namespace: "{{ backup_pvc_namespace }}"
        pod: "{{ meta.name }}-backup-manager"
        command: >-
          bash -c "cat '{{ backup_dir }}/{{ objstorage_file }}'"
      register: objectstorage_secret
      no_log: true

    - name: Create temp vars file
      tempfile:
        prefix: secret_vars-
      register: secret_vars_obj

    - name: Write vars to file locally
      copy:
        dest: "{{ secret_vars_obj.path }}"
        content: "{{ objectstorage_secret.stdout }}"
        mode: 0640
      no_log: true

    - name: Include secret vars from backup
      include_vars: "{{ secret_vars_obj.path }}"
      no_log: true

    - name: Apply s3 secret
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/s3_secret.yaml.j2') }}"
      no_log: true
      when:
        - storage_type | lower == 's3'
        - storage_secret is defined
        - storage_secret | length

    - name: Apply azure secret
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/azure_secret.yaml.j2') }}"
      no_log: true
      when:
        - storage_type | lower == 'azure'
        - storage_secret is defined
        - storage_secret | length
  when:
    - objstorage_file in stat_backup_objectstorage.stdout

- name: Set name of DB fields encryption file name
  set_fact:
    db_fields_encryption_file: 'db_fields_encryption_secret.yaml'

- name: Set name of container token file name
  set_fact:
    container_token_file: 'container_token_secret.yaml'

- name: Check to if container token secret exists in  backup directory on PVC
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ meta.name }}-backup-manager"
    command: >-
      bash -c "stat {{ backup_dir }}/{{ container_token_file }}"
  register: stat_backup_container_token

- name: Create container token secret
  block:
    - name: Get secret definition from pvc
      k8s_exec:
        namespace: "{{ backup_pvc_namespace }}"
        pod: "{{ meta.name }}-backup-manager"
        command: >-
          bash -c "cat '{{ backup_dir }}/{{ container_token_file }}'"
      register: cont_token_secret
      no_log: true

    - name: Create temp vars file
      tempfile:
        prefix: secret_vars-
      register: secret_vars_cont

    - name: Write vars to file locally
      copy:
        dest: "{{ secret_vars_obj.path }}"
        content: "{{ cont_token_secret.stdout }}"
        mode: 0640
      no_log: true

    - name: Include secret vars from backup
      include_vars: "{{ secret_vars_cont.path }}"
      no_log: true

    - name: Apply DB fields encryption secret
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/db_fields_encryption_secret.yaml.j2') }}"
      no_log: true
      when:
        - db_fields_encryption_secret is defined
        - db_fields_encryption_secret | length

    - name: Apply container token secret
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/container_token_secret.yaml.j2') }}"
      no_log: true
      when:
        - container_token_secret is defined
        - container_token_secret | length
  when:
    - container_token_file in stat_backup_container_token.stdout
