---
- name: "Ansible | List all known variables and facts"
  debug:
    var: hostvars[inventory_hostname]

- name: Set the resource pod name as a variable.
  set_fact:
    storage_claim: "{{ deployment_name }}-file-storage"

- name: Delete any existing management pod
  k8s:
    name: "{{ ansible_operator_meta.name }}-backup-manager"
    kind: Pod
    namespace: "{{ backup_pvc_namespace }}"
    state: absent
    force: true
    wait: true

- name: Create management pod from templated deployment config
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/management-pod.yaml.j2') | from_yaml }}"
    wait: true

- name: Set file copy command
  set_fact:
    copy_cmd: >-
      cp -fr {{ backup_dir }}/pulp/. /var/lib/pulp

- name: Write content files from backup on PVC
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-backup-manager"
    command: >-
      bash -c "{{ copy_cmd }}"
  register: file_copy
