[allowlist]
  description = "Our test install exports a test only PRIVATE KEY"
  paths = [
    ".ci/assets/kubernetes/pulp-container-auth.secret.yaml",
    ".ci/assets/kubernetes/galaxy_sign.secret.yaml",
    ".ci/scripts/prepare-object-storage.sh",
    "containers/compose/certs/database_fields.symmetric.key",
  ]
