dist: xenial
sudo: required
services: docker
language: python
services:
  - docker
before_install:
  - git clone https://github.com/pulp/pulp_file.git
install:
  - pip install docker molecule openshift jmespath
  # Need /usr/bin/http script, so use sudo
  # It can mess up ownership of the python cache dir, so run it after the
  # non-sudo pip command.
  - sudo pip install httpie
  - .travis/k3s-install.sh
script:
  - sudo ./up.sh
  - .travis/pulp-operator-check-and-wait.sh
  - .travis/pulp_file-tests.sh
after_failure:
  - http --timeout 30 --check-status --pretty format --print hb http://localhost:24817/pulp/api/v3/status/
  # With the selector (which eliminates the need to look up the pod name),
  # we cannot show all logs. 10000 lines should be sufficient.
  - sudo kubectl logs -l app=pulp-api --tail=10000
