dist: bionic
sudo: required
language: python
services:
  - docker
addons:
  apt:
    packages:
      - httpie
      - jq
before_install:
  .travis/before_install.sh
  # Created template_config.yml with plugin_template,
  # and after that I removed manually travis files not related to validating commit
  # also removed some python related stuff like flake8, black and pip installing doc/test requirements
install:
  # Need /usr/bin/http script, so use sudo
  # It can mess up ownership of the python cache dir, so run it after the
  # non-sudo pip command.
  - .travis/k3s-install.sh
  - export IMG="quay.io/pulp/pulp-operator:latest"
jobs:
  include:
    - name: test-all-components
      script:
        - sudo make docker-build
        - sudo docker images
        - sudo ./up.sh
        - .travis/pulp-operator-check-and-wait.sh
        # This step will run indefinitely if we do not limit it to 5 mins.
        # If the entire build reaches 50 mins, the after_failure steps never run.
        - .travis/pulp_file-tests.sh
    - name: test-insta-demo
      script:
        - sudo make docker-build
        - sudo docker images
        - sudo insta-demo/pulp-insta-demo.sh
    - name: molecule
      install:
        - pip3 install docker molecule molecule-docker ansible-lint yamllint flake8 openshift jmespath
      before_script: skip
      script: .travis/molecule.sh
    - stage: deploy
      name: push-to-quay
      # Push image to quay. That is our upstream "deployment".
      script:
        - sudo make docker-build
        - sudo .travis/deploy.sh
      if: type != pull_request
after_failure:
  - http --timeout 30 --check-status --pretty format --print hb http://localhost:24817/pulp/api/v3/status/
  - sudo docker images
  # With the selector (which eliminates the need to look up the pod name),
  # we cannot show all logs. 10000 lines should be sufficient.
  - sudo kubectl logs -l name=controller-manager -c manager --tail=10000
  - sudo kubectl logs -l app=pulp-api --tail=10000
  - sudo kubectl logs -l app=pulp-content --tail=10000
  - sudo kubectl logs -l app=pulp-worker --tail=10000
  - sudo kubectl logs -l app=pulp-resource-manager --tail=10000
