dist: bionic
sudo: required
language: python
services:
  - docker
addons:
  apt:
    packages:
      - httpie
      - jq
before_install:
  .travis/before_install.sh
  # Created template_config.yml with plugin_template,
  # and after that I removed manually travis files not related to validating commit
  # also removed some python related stuff like flake8, black and pip installing doc/test requirements
install:
  # Need /usr/bin/http script, so use sudo
  # It can mess up ownership of the python cache dir, so run it after the
  # non-sudo pip command.
  - .travis/k3s-install.sh
  - CURRENT_VERSION=$(head -1 ./build/Dockerfile  | cut -d ":" -f 2)
  - SDK_LATEST_VERSION=$(http https://api.github.com/repos/operator-framework/operator-sdk/releases/latest | jq -r '.tag_name')
  - sed -i "s/$CURRENT_VERSION/$SDK_LATEST_VERSION/g" ./build/Dockerfile
  - sudo wget https://github.com/operator-framework/operator-sdk/releases/download/$SDK_LATEST_VERSION/operator-sdk-$SDK_LATEST_VERSION-x86_64-linux-gnu -O /usr/local/bin/operator-sdk
  - sudo chmod +x /usr/local/bin/operator-sdk
jobs:
  include:
    - name: test-all-components
      script:
        - sudo operator-sdk build quay.io/pulp/pulp-operator:latest
        - sudo docker images
        - sudo ./up.sh
        - .travis/pulp-operator-check-and-wait.sh
        # This step will run indefinitely if we do not limit it to 5 mins.
        # If the entire build reaches 50 mins, the after_failure steps never run.
        - .travis/pulp_file-tests.sh
      deploy:
        provider: script
        # Push image to quay. That is our upstream "deployment".
        script: sudo .travis/deploy.sh
        on:
          # Only run on the master branch, because "latest" is hardcoded
          branch: master
          # Also, deploy will never run on PRs.
          # "Note that pull request builds skip the deployment step altogether."
          # https://docs.travis-ci.com/user/deployment#pull-requests
    - name: test-insta-demo
      script:
        - sudo operator-sdk build quay.io/pulp/pulp-operator:latest
        - sudo docker images
        - sudo insta-demo/pulp-insta-demo.sh
after_failure:
  - http --timeout 30 --check-status --pretty format --print hb http://localhost:24817/pulp/api/v3/status/
  - sudo docker images
  # With the selector (which eliminates the need to look up the pod name),
  # we cannot show all logs. 10000 lines should be sufficient.
  - sudo kubectl logs -l name=pulp-operator -c pulp-operator --tail=10000
  - sudo kubectl logs -l app=pulp-api --tail=10000
  - sudo kubectl logs -l app=pulp-content --tail=10000
  - sudo kubectl logs -l app=pulp-worker --tail=10000
  - sudo kubectl logs -l app=pulp-resource-manager --tail=10000
