site_name: Pulp Operator
site_description: Pulp Operator
site_author: Pulp Team
site_url: https://pulp-operator.readthedocs.io/
repo_name: pulp/pulp-operator
repo_url: https://github.com/pulp/pulp-operator
theme: readthedocs
nav:
  - Home: index.md
  - Getting Started: quickstart.md
  - Contributing: contributing.md
  - Roles:
      - Pulp API: roles/pulp-api.md
      - Pulp Content: roles/pulp-content.md
      - Pulp Resource Manager: roles/pulp-resource-manager.md
      - Pulp Routes: roles/pulp-routes.md
      - Pulp Worker: roles/pulp-worker.md
      - Postgres: roles/postgres.md
      - Redis: roles/redis.md
  - Changelog: CHANGES.md
markdown_extensions:
  - pymdownx.superfences
