site_name: Pulp Operator
site_description: Pulp Operator
site_author: Pulp Team
site_url: https://pulpproject.org/pulp_operator/
repo_name: pulp/pulp-operator
repo_url: https://github.com/pulp/pulp-operator
theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
  name: material
  custom_dir: "docs/overrides"
  logo: images/pulp_logo_big.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting Started: quickstart.md
  - Contributing: contributing.md
  - Containers: container.md
  - Architecture: architecture.md
  - Custom Resources:
      - Pulp: pulp.md
      - Pulp Backup: backup.md
      - Pulp Restore: restore.md
  - Installing:
      - Helm Chart: install/helm.md
      - OpenShift: install/ocp.md
      - Highly Available Pulp: install/ha.md
  - Configuring:
      - Pulp Settings: configuring/pulp_settings.md
      - Database: configuring/database.md
      - Storage: configuring/storage.md
      - Cache: configuring/cache.md
      - Networking:
        - Exposing Pulp: configuring/networking/exposing.md
        - Reverse Proxy: configuring/networking/reverse_proxy.md
        - Routes: configuring/networking/routes.md
      - Pod Placement: configuring/podPlacement.md
      - LogLevel: configuring/logLevel.md
      - Custom CA: configuring/customCA.md
      - Pod Disruption Budget: configuring/pdb.md
      - Secrets: configuring/secrets.md
      - Reseting Pulp Admin Password: configuring/reset_admin_pwd.md
      - Disabling Reconciliation: configuring/unmanaged.md
      - Galaxy: configuring/galaxy.md
      - Telemetry: configuring/telemetry.md
      - Content Checksums: configuring/content_checksums.md
      - LDAP Authentication: configuring/ldap.md
      - Metadata Signing: configuring/metadata_signing.md
      - Custom Environment Variables: configuring/custom_env_vars.md
  - Backup and Restore:
      - Overview: backup_and_restore/overview.md
      - Configuring and Running: backup_and_restore/config_running.md
      - Scheduling backups: backup_and_restore/cronjob.md
  - Changelog: CHANGES.md
  - FAQ: faq.md
  - Troubleshooting:
      - Troubleshooting installations: tshoot/install.md
      - Gathering data: tshoot/gatherData.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - admonition
extra:
  version:
    provider: mike
    default: latest
plugins:
  - git-revision-date
  - search:
      lang: en
      prebuild_index: true
