- hosts: localhost
  gather_facts: no
  vars:
    project_name: "{{ meta.namespace }}"
    deployment_state: present
    registry: quay.io/mikedep333
  roles:
    - postgres
    - redis
    - pulp-api
    - pulp-resource-manager
    - pulp-worker
