[tool.towncrier]
package = "pulp-operator"
filename = "CHANGES.md"
directory = "CHANGES/"
title_format = "{version} ({project_date})"
template = "CHANGES/.TEMPLATE.md"
issue_format = "[#{issue}](https://github.com/pulp/pulp-operator/issues/{issue})"
start_string = "<!-- TOWNCRIER -->\n"
