[tool.towncrier]
package = "pulp-operator"
filename = "docs/CHANGES.md"
directory = "CHANGES/"
title_format = "{version} ({project_date})"
template = "CHANGES/.TEMPLATE.md"
issue_format = "[#{issue}](https://pulp.plan.io/issues/{issue})"
start_string = "<!-- TOWNCRIER -->\n"
