- name: Gathering routes
  vars:
    max_retries: "{{ 5 if max_retries is undefined else max_retries | int }}"
    retry_delay: "{{ 10 if retry_delay is undefined else retry_delay | int }}"
  block:
  - name: Increment the retry count
    set_fact:
      retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

  - set_fact:
      _pulp_default_plugins:
        - { name: "{{ ansible_operator_meta.name }}-content", path: "{{ pulp_combined_settings.content_path_prefix | default('/pulp/content/') }}", targetPort: "content-24816", serviceName: "{{ ansible_operator_meta.name }}-content-svc" }
        - { name: "{{ ansible_operator_meta.name }}-api-v3", path: "{{ pulp_combined_settings.api_root }}api/v3/", targetPort: "api-24817", serviceName: "{{ ansible_operator_meta.name }}-api-svc" }
        - { name: "{{ ansible_operator_meta.name }}-auth", path: "/auth/login/", targetPort: "api-24817", serviceName: "{{ ansible_operator_meta.name }}-api-svc" }
        - { name: "{{ ansible_operator_meta.name }}", path: "/", targetPort: "api-24817", serviceName: "{{ ansible_operator_meta.name }}-api-svc" }

  - name: Get API pod
    k8s_info:
      kind: Pod
      namespace: "{{ ansible_operator_meta.namespace }}"
      label_selectors:
        - "app.kubernetes.io/component = api"
    register: _pod_list

  - name: Get routes from plugins
    k8s_exec:
      namespace: "{{ ansible_operator_meta.namespace }}"
      pod: "{{ _pod_list.resources[0].metadata.name }}"
      command: "/usr/bin/route_paths.py {{ ansible_operator_meta.name }}"
    register: _route_paths_output

  - set_fact:
      _pulp_plugins: "{{ _pulp_default_plugins + _route_paths_output.stdout | from_json }}"

  rescue:
    - fail:
        msg: Maximum retries reached
      when: retry_count | int == max_retries | int

    - debug:
        msg: "Task Group failed, let's give it another shot"

    - name: Sleep between retries
      wait_for:
        timeout: "{{ retry_delay }}" # seconds
      delegate_to: localhost
      become: false

    - include_tasks: load_routes.yml
