---
apiVersion: v1
kind: Secret
metadata:
  name: signing-galaxy
stringData:
  signing_service.gpg: |-
      -----BEGIN PGP PRIVATE KEY BLOCK-----

      lQcYBGJFjREBEACS1aBb6sqz1kfO/IicOrut0JfMybZTrbeB5d45zGIQW6URdUQo
      Xz5Y/CAzf3w3+njKQUGUWHHjfDNUuHyAAx4B4jJV3KcoTTYb7NWJLEe76+iXDClk
      vKrYx7MmOyjTm10p/QFOpBQGjhXS9+eVId6+AeUK0MgJba3ddBRH2OWMcpX1t22h
      6z6bHj5oUUQiwOxgYSuiMfs24BHujXsochpa0ylxSptn2j/jKz+kj1uZChafDDhg
      TovXGL1L80pbmHfcGVufFtavQgSwd3c0/8Cicnb7nwiUL0Thldl/apgj61vGbkEN
      GueSxdKmFEvOhF8Jsn38x7Bw4G/RtbGxuiz5iOuF36pBlqAl5IavsdQktvb8ydmP
      2Hr6ihd0/L8dFZsQ/W1oN6wn+xgNG+IuQBdakUc9EF8gx3Y9SjFNP+BRuiiOUzXW
      uj2ipzDi2ROwdNyQaq7BfxK/NqpJHY56/HjDZ9lgBnloT+VcV42zahT2Bu1PZLlN
      YbLtsqtSg1CDDbtrNzeCgQO9Pgvz4zHaQXOYXdHU8SamkLzGPEjcqXpOEEopLxU9
      WVkea5M8ejp43J6vd6vW/tzZY8xDWjoDjqMqDL586Ii6MBliIev3hMTLHC0kc9HC
      ZK/AcYgXH0qsL8XK5M7oZC1FZ0sGMWo5M1xQLWjv3YDugAMWrgvM6vFAUwARAQAB
      AA/+Kvz2JNL5o2sBvPy8NhkP51RhjOglRBxg1FvrErrenvFlw1W0raksxLqT5t/V
      C0J+aKBwRbEbLsGm+Y/Fi2jeOSjzGaYvHiJ0y/orjixzl/X6M3axC7gcwLi+n1vE
      mScsQGW9IzvwTPb+NrSzjTrMTo6ZcvArEG+W7nXUljBPDC5j7vtT0orf2mQhW0Mn
      kpEu4wyvzJ2bcbZqKZAsVWwKgTq/MFbqZp5EBAseZ9w8sfJ9KvVV8AQu9rtceEbz
      JxvdQ4f9BfeWxNqsKsnfEZoq2KRwZzxpM5EfNng7pA0eG64FQXP4AZE16QeXo13f
      z8d7V4h1UDNaWcGrmxb5vhHGppoCyw1l9qo/tK+A/6OTE2oQwZNvC7OOUteDxMsl
      bhMTtLPNewa09esq6KiDOZ7vlL3Fn40NQmW0aK5hX+AAeEjMR/7qMWRWWmbhwPf9
      3UnFbQuoHnlFytWGzKnbx+dqg2iYkOnpe0uiSVthzhRbkoCijZDjgUlkBdHcOpOJ
      0gxspuSzuKtGWDv7mJEOz2lVIWzdr80sVEfjahTEMCsQPGz0OKrN/dTlDsQIa10y
      XXjadUcDAfaT6FIFxJWYcdFVYXWts5uHDcb53bjpfVsQE3mzSnYnTF7KoarYD2SY
      BYs+IYlf1YGc9UjwfU+PysUbbmeY8hrtUQqwWsbrl+2GlcEIALVQXzZlQfjdjYZt
      u4Z4ZrvaCoH8tUiquyaUgnmuXL4w2CZw2DH6ohJWvH859rHpnbZnqB8lZ+5fMPZ5
      K/FuUwtSdZP5zE8Auq67VHy5I1UPImui4+AQPz4d1ALyAf4RKCUBGJkX3G3t51jf
      UgRkCKeuJE/oCF0/k/nHpb5tg2R2XDZDqhxRtqJwoASqP4nwWQjWbFbKgLntQ6RU
      +apw5g5KHAaf5J1wVFHCXFlXiCCeI0IgxaSJ4rSB3QIVAgyJz4o38gwaVPSOB1e6
      /mWP00cGzcOT5cpBRdzm/kuuI6Al/qx+hl5Me0/Ga/O9ggRV2FEf1U6ekzw5uUxk
      Quc5znMIAM9RYVagbtJxtvIKty/mCTCghTDkZ1sSHRMFr1/TREpsIgfpHJhMr7xe
      DMznl2sLpvtsg07Z9TkCyg7s3nuax1XSY+bmHJxeL3uE6kebyq1sEqdAWlO3Gcpx
      PIlwuebZkOSDv5Gj7ANNKyLL+yOf1mg2Sv2IuY0PF9bUN/WzffTwNdNF/UIjdLD7
      xbKWmEzLDyqDBl1v3J0AjpzVF+ihJ+UsC9Y4eGI1x4mz2b4abB8mc5znGpCJLM1j
      y6lRsoLRHuih7jSMenkmnEbwig17g+4yTfhOlgjF3X6ay9UZq284Tc7B8P5p218h
      JSk0w2Svgljin/8x0vWHP0OaPSJbbqEH/jwK+MsxiKFy+yyDdymDlepqgwJz2tYa
      sE22rk0BuelgNu23UZOjNZZXxflnaZx2E0+nleDjx0hG2QpoR437jwR0TiWFtTCF
      TteSqxjLpIG3BTxazTTpRX30y7vseJo5pon/zNaQTBTONfpRSOcxeArhL9hboRTc
      cbQRfLOe9ZnIITC9XSbWoP08Qa8IbuUp3U0EWHaExMxoR4ytgnNXQzmnXIlQv6yq
      rYuB11nR8e8wkYiCZrHuZ2t5xIutxHHUsQ7LqKbHbO6/EUltlwrOvC1PnK+6tBz7
      MJAJG39pBHB0cv14W37MgblCfK1xsQRZx6RBX4GIlmZ0l8UwxoFSoT+I+LQtSm9l
      IFRlc3RlciAod2l0aCBubyBwYXNzcGhyYXNlKSA8am9lQGZvby5iYXI+iQJOBBMB
      CAA4FiEEL/Z8+SXD5KDc9SVn7nR1FlE418IFAmJFjRECGwMFCwkIBwIGFQoJCAsC
      BBYCAwECHgECF4AACgkQ7nR1FlE418Kcaw/+Pq0a14EhLbbce5euQEvoDKNaIsMU
      OE4b9o0yJz3t5P0CFUl9qUx+lSu8KhFUWObuSTlQFBuDfWBVWe9/bpC3iGHnTUuc
      QbDUH/svXIQYeBnLIJb62CLSZEWEU/fonxzRSt86UA41vdTkro7XQlk+Z2uMvGsP
      qg18Zn9kecgPyUcgge5dIacgunvyQE0BN47KD+JZBLFm9lgwCs+YHiu9SKYGBJt5
      I3RXL8vIyo2JTUyNn8IiNnvUC5bcG38tzzaAphROJTEV7fn6e1HHrebRk1SL2nvZ
      XL0kScWUOMR4JIOsxsmYPslofNpio6c+EdF26iKX61L3IvLHhHQRpuCrBPCH0LbE
      8FajpC5fZXnhyY1f8Dp9z8WqrAZGx3M9+FkABs22I2u4ojKb8l5Mhl4mNCMH5R2W
      MfjH/n9VZsWvUfrBB3I+tU/+fjoX4OlMTnIBS3FNQ8xoGNJkpWKYXczwTaRdX9UR
      tz43QpDN7oqRCgQGlVdsX7HWWhFafVU9ODw7wyp4ZNHutptymskaTtmaeVTJflQr
      wIDOctd42CP3QQU+u6Dob7wZPD9tONxSOY3e9Tb1bN+7i6ohN9mv4Zh30K3bLkZh
      eXxVrgGcz1H7S7WZBSReHOpww6ByMx4AJfyvtfe8FnbhVDpaccqsMnSDU294yH9C
      PB/lOYgJsKJHqIOdA5gEYkWNEQEIAMD8aVvEMFrvvxNT5JbZUxmXXb3M5iu51GTF
      lcja/57eMfQxx/nc31UsI/VzZJQtMM1qJfzW4cbgCfQpVZ4kIxtKV5WgKxMxo0De
      sALeIJrpX7ZlxQqLXC/a4vhaCdT08nbSfsthpgk38P21UuSBsEJgW7jNMPmECnqI
      Bw32Ke2st5gdE6wGHgUt3CgrQAygmirNYDTucijjbkrt2Iq/VZaGSAcvgvcpoL7w
      QDL9TRPVWwD2C2pXGAjJXQl50JNBa8kTCNFGgFWNe8STqPicj4cdqDnDpcxxwYZ4
      yPap5hMg9wNxdYF2mflc6tTRcKs7lDRMci4rdBmEveXxHKbLZaEAEQEAAQAH/A4P
      9n9s1tcxhBtc8Bm74U3KlVaYwSbrhhoHucfmiVzitQIlxHwlB5MVwdMHYwtXFajK
      NNVtNQuAVMlZX7dDy9kXvDUXdDwUUGCQOYQj+n0/Ry2r0cVYbVHBYeuV6ASACtD0
      uq+IQIiIboOWPGGRP64+hkB7lzd/UyIlmln+l4SNgmfPR8CKD+ZFdWhgOLEda4Tj
      Ny7+VWOhMM+PcyVf2Oc/2QWEeN1A4H/E7i7Z/4yuDygN+J2leQTRqzCZEZ1DfneW
      Kn8CyRpUpEgjUEI5FQkcnkztL8hGheYISt+WNQtGGqlglmcMZqB0FdaMBB7kMkLG
      MSVaqUGzyyVEy7HV5hcEANCIkw8ab9ulxRfaQGOSqcJwWUFodfJAU2jJhVpNCq58
      48O/Dw34NKhZUiH3Ra/DYV0d72+N22+OktADNL/q44WeqrPMZ0918kt98akYB3Is
      A9507nEJ0AsNT+LJd9Y6zSDslg781s/jqgz/JeYDm1IUeWG3AOIDiBrom2n9Xicr
      BADs6d7LPuh+4Id5WArOrnB/GXxzzuHRGSBOzK9ncNH81tqaFIfKbu3M3DoQMy8c
      Fc0fQEStMmIovkHO0A8tv5l/ZZUdxIBoYJJIpu6+UGNoPAAdeUZHXSoGo7akFe0C
      Vku+vpRvyOc2FXIzcBe8/yYv5kep6bU4Fk5JyMa66QbAYwQAxr/7F8PtZdSZ4l2+
      XFxPLC0NQnBt4oIMYyKp/cKXpumHMObyTSHUl4IRd33mahi37gAc2pNq+YAw+XKq
      GPaW3jOr8ggn42SO9v1kD/xykl98pfUR/24gScz/7GyTYBaTgKEY6QDCIwt4la+F
      zlQQR99HYeD53P6AWHQ6Kc4xHOM4M4kCNgQYAQgAIBYhBC/2fPklw+Sg3PUlZ+50
      dRZRONfCBQJiRY0RAhsMAAoJEO50dRZRONfCI5AP/1vyfvhtPrwLn4RQQiCRxOW7
      qHEXlD0exhBhG3rdrfF5F0oSnroeyCtWxc0UL6MuVmervCzQJqEHjrcdBTnMdov2
      X9iLq96xREhwSa6LFjqacy5gyeoxULLiDWAP3lXlPL2C/qpL0muwLAIZvQu3eDo9
      jMFmHcjl5oXcXxjvCF6o+yDXzVnS1P7B/UQw7a+zqiw2SZ65kEqsL5ROCk+A4zsr
      gIUE5l1vpPt3HFWSY69bc8uWc6Ia/QrydeJaltrcDEY4myIpq+fEjtGBEvWZL81I
      mHlp//Bciy/IxD1mX75KCFDMyQ289IJsv6RnOIxEMpQdGPTZ5LkK1ZIffMs+KO2t
      XM24r84ezgdc0rTzf6eFPthDdSgNyKjcwFWHBhwGXb8McMCs78Lt6cRtFGUY4RHv
      nlpfxvuBpgOhiHbLkHfyfe5+5Wr/nK7q9N+zvuYlJ5M320oQIjNH0ozKd/jdOQhl
      XdJPzcZlSRjUMIME28fbOFtAjMK0nldJIIylg/ePRxmdIK4lB/rg7qvFgNqCtwG2
      3BT+LmSE9SjU4s0RiZQsyI2dngbyucWETH2sbeCfv5tAEMQWVzjthNd5B0Yb9zE6
      ad6Kx9AwPmyfNxmUsaJx/qPsXnFtjhAL52QhGkwna3wSOgh1dkb9famrM8e2hCXU
      10cGjWOK57nPi2EBA9d0
      =o1YT
      -----END PGP PRIVATE KEY BLOCK-----
  signing_service.asc: |-
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBGJFjREBEACS1aBb6sqz1kfO/IicOrut0JfMybZTrbeB5d45zGIQW6URdUQo
      Xz5Y/CAzf3w3+njKQUGUWHHjfDNUuHyAAx4B4jJV3KcoTTYb7NWJLEe76+iXDClk
      vKrYx7MmOyjTm10p/QFOpBQGjhXS9+eVId6+AeUK0MgJba3ddBRH2OWMcpX1t22h
      6z6bHj5oUUQiwOxgYSuiMfs24BHujXsochpa0ylxSptn2j/jKz+kj1uZChafDDhg
      TovXGL1L80pbmHfcGVufFtavQgSwd3c0/8Cicnb7nwiUL0Thldl/apgj61vGbkEN
      GueSxdKmFEvOhF8Jsn38x7Bw4G/RtbGxuiz5iOuF36pBlqAl5IavsdQktvb8ydmP
      2Hr6ihd0/L8dFZsQ/W1oN6wn+xgNG+IuQBdakUc9EF8gx3Y9SjFNP+BRuiiOUzXW
      uj2ipzDi2ROwdNyQaq7BfxK/NqpJHY56/HjDZ9lgBnloT+VcV42zahT2Bu1PZLlN
      YbLtsqtSg1CDDbtrNzeCgQO9Pgvz4zHaQXOYXdHU8SamkLzGPEjcqXpOEEopLxU9
      WVkea5M8ejp43J6vd6vW/tzZY8xDWjoDjqMqDL586Ii6MBliIev3hMTLHC0kc9HC
      ZK/AcYgXH0qsL8XK5M7oZC1FZ0sGMWo5M1xQLWjv3YDugAMWrgvM6vFAUwARAQAB
      tC1Kb2UgVGVzdGVyICh3aXRoIG5vIHBhc3NwaHJhc2UpIDxqb2VAZm9vLmJhcj6J
      Ak4EEwEIADgWIQQv9nz5JcPkoNz1JWfudHUWUTjXwgUCYkWNEQIbAwULCQgHAgYV
      CgkICwIEFgIDAQIeAQIXgAAKCRDudHUWUTjXwpxrD/4+rRrXgSEtttx7l65AS+gM
      o1oiwxQ4Thv2jTInPe3k/QIVSX2pTH6VK7wqEVRY5u5JOVAUG4N9YFVZ739ukLeI
      YedNS5xBsNQf+y9chBh4GcsglvrYItJkRYRT9+ifHNFK3zpQDjW91OSujtdCWT5n
      a4y8aw+qDXxmf2R5yA/JRyCB7l0hpyC6e/JATQE3jsoP4lkEsWb2WDAKz5geK71I
      pgYEm3kjdFcvy8jKjYlNTI2fwiI2e9QLltwbfy3PNoCmFE4lMRXt+fp7Ucet5tGT
      VIvae9lcvSRJxZQ4xHgkg6zGyZg+yWh82mKjpz4R0XbqIpfrUvci8seEdBGm4KsE
      8IfQtsTwVqOkLl9leeHJjV/wOn3PxaqsBkbHcz34WQAGzbYja7iiMpvyXkyGXiY0
      IwflHZYx+Mf+f1Vmxa9R+sEHcj61T/5+Ohfg6UxOcgFLcU1DzGgY0mSlYphdzPBN
      pF1f1RG3PjdCkM3uipEKBAaVV2xfsdZaEVp9VT04PDvDKnhk0e62m3KayRpO2Zp5
      VMl+VCvAgM5y13jYI/dBBT67oOhvvBk8P2043FI5jd71NvVs37uLqiE32a/hmHfQ
      rdsuRmF5fFWuAZzPUftLtZkFJF4c6nDDoHIzHgAl/K+197wWduFUOlpxyqwydINT
      b3jIf0I8H+U5iAmwokeog7kBDQRiRY0RAQgAwPxpW8QwWu+/E1PkltlTGZddvczm
      K7nUZMWVyNr/nt4x9DHH+dzfVSwj9XNklC0wzWol/NbhxuAJ9ClVniQjG0pXlaAr
      EzGjQN6wAt4gmulftmXFCotcL9ri+FoJ1PTydtJ+y2GmCTfw/bVS5IGwQmBbuM0w
      +YQKeogHDfYp7ay3mB0TrAYeBS3cKCtADKCaKs1gNO5yKONuSu3Yir9VloZIBy+C
      9ymgvvBAMv1NE9VbAPYLalcYCMldCXnQk0FryRMI0UaAVY17xJOo+JyPhx2oOcOl
      zHHBhnjI9qnmEyD3A3F1gXaZ+Vzq1NFwqzuUNExyLit0GYS95fEcpstloQARAQAB
      iQI2BBgBCAAgFiEEL/Z8+SXD5KDc9SVn7nR1FlE418IFAmJFjRECGwwACgkQ7nR1
      FlE418IjkA//W/J++G0+vAufhFBCIJHE5buocReUPR7GEGEbet2t8XkXShKeuh7I
      K1bFzRQvoy5WZ6u8LNAmoQeOtx0FOcx2i/Zf2Iur3rFESHBJrosWOppzLmDJ6jFQ
      suINYA/eVeU8vYL+qkvSa7AsAhm9C7d4Oj2MwWYdyOXmhdxfGO8IXqj7INfNWdLU
      /sH9RDDtr7OqLDZJnrmQSqwvlE4KT4DjOyuAhQTmXW+k+3ccVZJjr1tzy5Zzohr9
      CvJ14lqW2twMRjibIimr58SO0YES9ZkvzUiYeWn/8FyLL8jEPWZfvkoIUMzJDbz0
      gmy/pGc4jEQylB0Y9NnkuQrVkh98yz4o7a1czbivzh7OB1zStPN/p4U+2EN1KA3I
      qNzAVYcGHAZdvwxwwKzvwu3pxG0UZRjhEe+eWl/G+4GmA6GIdsuQd/J97n7lav+c
      rur037O+5iUnkzfbShAiM0fSjMp3+N05CGVd0k/NxmVJGNQwgwTbx9s4W0CMwrSe
      V0kgjKWD949HGZ0griUH+uDuq8WA2oK3AbbcFP4uZIT1KNTizRGJlCzIjZ2eBvK5
      xYRMfaxt4J+/m0AQxBZXOO2E13kHRhv3MTpp3orH0DA+bJ83GZSxonH+o+xecW2O
      EAvnZCEaTCdrfBI6CHV2Rv19qaszx7aEJdTXRwaNY4rnuc+LYQED13Q=
      =Qkz7
      -----END PGP PUBLIC KEY BLOCK-----
