---
apiVersion: v1
kind: Secret
metadata:
  name: 'example-pulp-object-storage'
  namespace: 'default'
stringData:
  s3-access-key-id: 'myaccesskey'
  s3-secret-access-key: 'mysecret'
  s3-bucket-name: 'mybucket'
  s3-region: 'us-east-1'
