---

- name: Write pulp object to pvc
  k8s_exec:
    namespace: "{{ meta.namespace }}"
    pod: "{{ meta.name }}-backup-manager"
    command: >-
      bash -c "echo '{{ cr_spec }}' > {{ _backup_dir }}/cr_object"

- name: Get admin_password
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ admin_password_secret }}'
  register: _admin_password

- name: Set admin_password
  set_fact:
    admin_password: "{{ _admin_password['resources'][0]['data']['password'] | b64decode }}"

- name: Get postgres configuration
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ postgres_configuration_secret }}'
  register: _postgres_configuration

- name: Set postgres configuration
  set_fact:
    database_password: "{{ _postgres_configuration['resources'][0]['data']['password'] | b64decode }}"
    database_username: "{{ _postgres_configuration['resources'][0]['data']['username'] | b64decode }}"
    database_name: "{{ _postgres_configuration['resources'][0]['data']['database'] | b64decode }}"
    database_port: "{{ _postgres_configuration['resources'][0]['data']['port'] | b64decode }}"
    database_host: "{{ _postgres_configuration['resources'][0]['data']['host'] | b64decode }}"

- name: Set postgres db type
  set_fact:
    database_type: "{{ _postgres_configuration['resources'][0]['data']['type'] | b64decode }}"
  when:
    - _postgres_configuration['resources'][0]['data']['type'] is defined
    - _postgres_configuration['resources'][0]['data']['type'] | length

- name: Make temp secrets directory
  tempfile:
    prefix: "secrets-"
    state: directory
  register: secrets_dir

- name: Template default secrets configuration definition
  template:
    src: secrets.yaml.j2
    dest: "{{ secrets_dir.path }}/secrets.yaml"
    mode: '0600'

- name: Set default secret configuration
  set_fact:
    default_secret_template: "{{ lookup('file', '{{ secrets_dir.path }}/secrets.yaml') }}"

- name: Write default secret to pvc
  k8s_exec:
    namespace: "{{ meta.namespace }}"
    pod: "{{ meta.name }}-backup-manager"
    command: >-
      bash -c "echo '{{ default_secret_template }}' > {{ _backup_dir }}/secrets.yaml"

- name: Get container token configuration
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ container_token_secret }}'
  register: _container_token_configuration
  when: container_token_secret is defined

- name: Set container token configuration
  set_fact:
    container_auth_private_key: "{{ _container_token_configuration['resources'][0]['data']['container_auth_private_key.pem'] | b64decode }}"
    container_auth_public_key: "{{ _container_token_configuration['resources'][0]['data']['container_auth_public_key.pem'] | b64decode }}"
  when:
    - _container_token_configuration is defined
    - _container_token_configuration['resources'][0]['data']['container_auth_private_key.pem'] is defined
    - _container_token_configuration['resources'][0]['data']['container_auth_private_key.pem'] | length
    - _container_token_configuration['resources'][0]['data']['container_auth_public_key.pem'] is defined
    - _container_token_configuration['resources'][0]['data']['container_auth_public_key.pem'] | length

- name: Template container token configuration definition
  template:
    src: container_token_secret.yaml.j2
    dest: "{{ secrets_dir.path }}/container_token_secret.yaml"
    mode: '0600'
  when:
    - container_token_secret is defined

- name: Set container token configuration
  set_fact:
    container_token_secret_template: "{{ lookup('file', '{{ secrets_dir.path }}/container_token_secret.yaml') }}"
  when:
    - container_token_secret is defined

- name: Write container token secret to pvc
  k8s_exec:
    namespace: "{{ meta.namespace }}"
    pod: "{{ meta.name }}-backup-manager"
    command: >-
      bash -c "echo '{{ container_token_secret_template }}' > {{ _backup_dir }}/container_token_secret.yaml"
  when:
    - container_token_secret is defined

- name: Get objectstorage configuration
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ storage_secret }}'
  register: _objectstorage_configuration
  when: storage_secret is defined

- name: Set s3 common configuration values
  set_fact:
    s3_data_obj: "{{ _objectstorage_configuration['resources'][0]['data'] }}"
    s3_access_key_id: "{{ _objectstorage_configuration['resources'][0]['data']['s3-access-key-id'] | b64decode }}"
    s3_secret_access_key: "{{ _objectstorage_configuration['resources'][0]['data']['s3-secret-access-key'] | b64decode }}"
    s3_bucket_name: "{{ _objectstorage_configuration['resources'][0]['data']['s3-bucket-name'] | b64decode }}"
  when:
    - storage_secret is defined
    - storage_type | lower == 's3'

- name: Set s3 region value if found
  set_fact:
    s3_region: "{{ s3_data_obj['s3-region'] | b64decode }}"
  when:
    - storage_secret is defined
    - storage_type | lower == 's3'
    - s3_data_obj['s3-region'] is defined
    - s3_data_obj['s3-region'] | length

- name: Set s3 endpoint value if found
  set_fact:
    s3_endpoint: "{{ s3_data_obj['s3-endpoint'] | b64decode }}"
  when:
    - storage_secret is defined
    - storage_type | lower == 's3'
    - s3_data_obj['s3-endpoint'] is defined
    - s3_data_obj['s3-endpoint'] | length

- name: Template s3 configuration definition
  template:
    src: s3_secret.yaml.j2
    dest: "{{ secrets_dir.path }}/objectstorage_secret.yaml"
    mode: '0600'
  when:
    - storage_secret is defined
    - storage_type | lower == 's3'

- name: Set s3 configuration
  set_fact:
    s3_secret_template: "{{ lookup('file', '{{ secrets_dir.path }}/objectstorage_secret.yaml') }}"
  when:
    - storage_secret is defined
    - storage_type | lower == 's3'

- name: Write s3 secret to pvc
  k8s_exec:
    namespace: "{{ meta.namespace }}"
    pod: "{{ meta.name }}-backup-manager"
    command: >-
      bash -c "echo '{{ s3_secret_template }}' > {{ _backup_dir }}/objectstorage_secret.yaml"
  when:
    - storage_secret is defined
    - storage_type | lower == 's3'

- name: Set azure common configuration values
  set_fact:
    azure_data_obj: "{{ _objectstorage_configuration['resources'][0]['data'] }}"
    azure_account_name: "{{ _objectstorage_configuration['resources'][0]['data']['azure-account-name] | b64decode }}"
    azure-account-key: "{{ _objectstorage_configuration['resources'][0]['data']['azure-account-key'] | b64decode }}"
    azure-container: "{{ _objectstorage_configuration['resources'][0]['data']['azure-container'] | b64decode }}"
  when:
    - storage_secret is defined
    - storage_type | lower == 'azure'

- name: Set azure container path value if found
  set_fact:
    azure_container_path: "{{ azure_data_obj['azure-container-path'] | b64decode }}"
  when:
    - storage_secret is defined
    - storage_type | lower == 'azure'
    - azure_data_obj['azure-container-path'] is defined
    - azure_data_obj['azure-container-path'] | length

- name: Template azure configuration definition
  template:
    src: azure_secret.yaml.j2
    dest: "{{ secrets_dir.path }}/objectstorage_secret.yaml"
    mode: '0600'
  when:
    - storage_secret is defined
    - storage_type | lower == 'azure'

- name: Set azure configuration
  set_fact:
    azure_secret_template: "{{ lookup('file', '{{ secrets_dir.path }}/objectstorage_secret.yaml') }}"
  when:
    - storage_secret is defined
    - storage_type | lower == 'azure'

- name: Write azure secret to pvc
  k8s_exec:
    namespace: "{{ meta.namespace }}"
    pod: "{{ meta.name }}-backup-manager"
    command: >-
      bash -c "echo '{{ azure_secret_template }}' > {{ _backup_dir }}/objectstorage_secret.yaml"
  when:
    - storage_secret is defined
    - storage_type | lower == 'azure'
