apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: example-pulp
spec:
  # image: pulp
  tag: "latest"
  admin_password_secret: "example-pulp-admin-password"
  storage_type: File
  ingress_type: nodeport
  file_storage:
    # k3s local-path requires this
    access_mode: "ReadWriteOnce"
    # We have a little over 10GB free on GHA VMs/instances
    size: "10Gi"
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
