---
apiVersion: v1
kind: Service
metadata:
  name: pulp-api
  namespace: "{{ project_name }}"
  labels:
    app: pulp-api
spec:
  selector:
    app: pulp-api
  ports:
    - protocol: TCP
      targetPort: 24817
      name: pulp-api-24817
      port: 24817
