---
apiVersion: v1
kind: Deployment
metadata:
  name: pulp-api
  namespace: "{{ project_name }}"
  labels:
    app: pulp-api
spec:
  replicas: {{ pulp_api.replicas }}
  selector:
    matchLabels:
      app: pulp-api
  template:
    metadata:
      labels:
        app: pulp-api
    spec:
      #serviceAccountName: "{{ project_name }}-anyuid"
      volumes:
        - name: pulp-server
          configMap:
            name: pulp-server
            items:
              - path: settings.py
                key: settings.py
      containers:
        - name: pulp-api
          image: "{{ registry }}/pulp-api:{{ version }}"
          imagePullPolicy: Always
          env:
            # TODO: Replace with k8s secrets
            - name: PULP_ADMIN_PASSWORD
              value: "password"
          ports:
            - protocol: TCP
              containerPort: 24817
          volumeMounts:
            - name: pulp-server
              mountPath: "/etc/pulp/"
