images:
  - galaxy_master:
      image_name: galaxy
      tag: latest
      container_file: Containerfile.core
      pulpcore: git+https://github.com/pulp/pulpcore.git@3.17#egg=pulpcore
      plugins:
        - "git+https://github.com/ansible/galaxy_ng.git"
registry: quay.io
project: pulp
