---
galaxy_info:
  author: AutomationHub Team
  description: A role to backup a AutomationHub deployment
  issue_tracker_url: https://github.com/pulp/pulp-operator/issues/new
  license: GPL-2.0-or-later
  company: Red Hat
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Fedora
      versions:
        - 30
        - 31
        - 32
        - 33
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - pulp
    - pulpcore
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
collections:
- operator_sdk.util
- kubernetes.core
