apiVersion: repo-manager.pulpproject.org/v1alpha1
kind: Pulp
metadata:
  name: example-pulp
spec:
  deployment_type: pulp
  is_k8s: true
  image: quay.io/pulp/galaxy
  image_version: latest
  image_web: quay.io/pulp/galaxy-web
  # image_web_version: latest
  # no_log: false
  # admin_password_secret: "example-pulp-admin-password"
  # signing_secret: "signing-galaxy"
  # signing_scripts_configmap: "signing-scripts"
  # storage_type: File
  # ingress_type: nodeport
  container_token_secret: "container-auth"
  # k3s local-path requires this
  # file_storage_access_mode: "ReadWriteMany"
  # We have a little over 10GB free on GHA VMs/instances
  # file_storage_size: "10Gi"
  pulp_settings:
    api_root: "/api/galaxy/pulp/"
  api:
    replicas: 1
  database:
    replicas: 1
    type: postgres
  content:
    replicas: 1
    # resource_requirements:
    #   requests:
    #     cpu: 150m
    #     memory: 256Mi
    #   limits:
    #     cpu: 800m
    #     memory: 1Gi
  worker:
    replicas: 1
    # resource_requirements:
    #   requests:
    #     cpu: 150m
    #     memory: 256Mi
    #   limits:
    #     cpu: 800m
    #     memory: 1Gi
  # web:
  #   replicas: 1
  #   resource_requirements:
  #     requests:
  #       cpu: 100m
  #       memory: 256Mi
  #     limits:
  #       cpu: 800m
  #       memory: 1Gi
