## Append samples you want in your CSV to this file as resources ##
resources:
- repo-manager_v1alpha1_pulp.yaml
- simple.yaml
- galaxy.yaml
- repo-manager_v1alpha1_pulpbackup.yaml
- repo-manager_v1alpha1_pulprestore.yaml
- repo-manager.pulpproject.org_v1beta1_pulp.yaml
- repo-manager.pulpproject.org_v1beta2_pulp.yaml
- repo-manager.pulpproject.org_v1beta3_pulp.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
