apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: example-pulp
spec:
  image: quay.io/pulp/galaxy
  image_version: latest
  image_web: quay.io/pulp/galaxy-web
  image_web_version: latest
  admin_password_secret: "example-pulp-admin-password"
  storage_type: Azure
  ingress_type: nodeport
  ######## Enable Execution Environments ########
  container_token_secret: "container-auth"
  ###############################################
  object_storage_azure_secret: example-pulp-object-storage
  # k3s local-path requires this
  file_storage_access_mode: "ReadWriteMany"
  # We have a little over 10GB free on GHA VMs/instances
  file_storage_size: "10Gi"
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
