apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: example-pulp
#spec:
  # The registry to grab the pulp image from.
# image: quay.io/pulp/pulp
# image_version: stable
# Pulp settings.
# pulp_settings:
#    debug: "True"
  # The pulp adminstrator password secret.
# admin_password_secret:
  # PostgreSQL container settings secret.
# postgres_configuration_secret: pg_secret_name
  # Configuration for the persistentVolumeClaim for /var/lib/pulp
# storage_type: File
  # Select storage type: File, S3, Azure
  # If your K8s cluster is only 1 node, and its StorageClass /
  # provisioner does not support ReadWriteMany, then you must change
  # this to "ReadWriteOnce".
  #
  # If your K8s cluster is multiple nodes, and does not support
  # ReadWriteMany, then pulp-operator is currently incompatible.
  #
  # Reference on which support ReadWriteMany:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
# file_storage_access_mode: "ReadWriteMany"

  # How much space do you want to give Pulp for storing content under
  # /var/lib/pulp ?
  # https://docs.pulpproject.org/en/3.0/nightly/installation/configuration.html#media-root

  # For reference, epel7 x86_64 is currently (2019-07) 30G. So 100G
  # should be sufficient for a test deployment with only the RPM
  # content plugin.
# file_storage_size: "100Gi"
# object_storage_s3_secret: example-pulp-object-storage
  # Configuration for S3 credentals
# object_storage_azure_secret: example-pulp-object-storage
  # Configuration for Azure credentals
  # Values below are set in roles rather than in playbook.yaml
# api:
#   replicas: 1
#   log_level: INFO
# content:
#   replicas: 2
#   log_level: INFO
# worker:
#   replicas: 2
# resource_manager:
    # Waiting on this to be implemented:
    # https://pulp.plan.io/issues/3707
#   replicas: 1
