apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: galaxy-demo
spec:
  ingress_type: Ingress
  image: quay.io/pulp/galaxy
  image_version: stable
  image_web: quay.io/pulp/galaxy-web
  image_web_version: stable
  admin_password_secret: "example-pulp-admin-password"
  container_token_secret: "container-auth"
  pulp_settings:
    GALAXY_FEATURE_FLAGS:
      execution_environments: "True"
  storage_type: File
  # k3s local-path requires this
  file_storage_access_mode: "ReadWriteMany"
  # We have a little over 10GB free on GHA VMs/instances
  file_storage_size: "10Gi"
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
