images:
  - pulpcore_master:
      image_name: pulpcore
      tag: latest
      container_file: Containerfile.core
      # Must specify egg name here so that the Dockerfile can specify the
      # setuptools extra of postgres
      pulpcore: git+https://github.com/pulp/pulpcore.git#egg=pulpcore
  - pulp_master_plugins_master:
      image_name: pulp
      tag: latest
      container_file: Containerfile.core
      pulpcore: git+https://github.com/pulp/pulpcore.git#egg=pulpcore
      plugins:
        - "git+https://github.com/pulp/pulp-certguard.git"
        - "git+https://github.com/pulp/pulp_file.git"
        - "git+https://github.com/pulp/pulp_ansible.git"
        - "git+https://github.com/pulp/pulp_container.git"
        - "git+https://github.com/pulp/pulp_deb.git"
        - "git+https://github.com/pulp/pulp_python.git"
        - "git+https://github.com/pulp/pulp_rpm.git"
  - pulp_web_master:
      image_name: pulp-web
      tag: latest
      container_file: Containerfile.web
      base_image_name: pulp
      python_version: "3.9"
      plugin_snippets:
        - pulp_ansible
        - pulp_container
  - galaxy_master:
      image_name: galaxy
      tag: latest
      container_file: Containerfile.core
      pulpcore: git+https://github.com/pulp/pulpcore.git@3.10#egg=pulpcore
      plugins:
        - "git+https://github.com/pulp/pulp_ansible.git"
        - "git+https://github.com/pulp/pulp_container.git"
        - "git+https://github.com/ansible/galaxy_ng.git"
  - galaxy_web_master:
      image_name: galaxy-web
      tag: latest
      container_file: Containerfile.web
      base_image_name: galaxy
      python_version: "3.9"
      plugin_snippets:
        - pulp_ansible
        - pulp_container
        - galaxy_ng
registry: quay.io
project: pulp
