---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt
spec:
  kubernetesVersion: "1.34"
  workerNodeGroupConfigurations:
  - count: 1
    name: worker
    labels:
      worker: true
