---
- k8s_status:
    api_version: "{{ api_version }}"
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    conditions:
      - type: Pulp-API-Ready
        message: Checking Azure storage configurations
        reason: CheckingAzureStorageConfigs
        status: "False"
        lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

- name: Check for specified azure storage configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ object_storage_azure_secret  }}'
  register: _custom_azure_configuration
  no_log: "{{ no_log }}"

- name: Check azure secret data format
  set_fact:
    azure_secret_data_avaiable: true
  when:
    - _custom_azure_configuration is defined
    - _custom_azure_configuration.resources is defined
    - _custom_azure_configuration.resources[0] is defined
    - _custom_azure_configuration.resources[0].data is defined

- block:
  - k8s_status:
     api_version: "{{ api_version }}"
     kind: "{{ kind }}"
     name: "{{ ansible_operator_meta.name }}"
     namespace: "{{ ansible_operator_meta.namespace }}"
     conditions:
       - type: Pulp-API-Ready
         message: Unexpected format in Azure Secret
         reason: UnexpectedAzureSecretFormat
         status: "False"
         lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

  - name: Fail if azure secret object is an unexpected format
    fail:
      msg: "Cannot read the data for secret {{ object_storage_azure_secret  }}"

  when:
    - not azure_secret_data_avaiable

- name: Check if azure-account-name is found
  set_fact:
    azure_account_name_available: true
  when:
    - azure_secret_data_avaiable
    - _custom_azure_configuration.resources[0].data['azure-account-name'] is defined
    - _custom_azure_configuration.resources[0].data['azure-account-name'] | length

- name: Check if azure-account-key is found
  set_fact:
    azure_account_key_available: true
  when:
    - azure_secret_data_avaiable
    - _custom_azure_configuration.resources[0].data['azure-account-key'] is defined
    - _custom_azure_configuration.resources[0].data['azure-account-key'] | length

- name: Check if azure-container is found
  set_fact:
    azure_container_available: true
  when:
    - azure_secret_data_avaiable
    - _custom_azure_configuration.resources[0].data['azure-container'] is defined
    - _custom_azure_configuration.resources[0].data['azure-container'] | length

- block:
  - k8s_status:
      api_version: "{{ api_version }}"
      kind: "{{ kind }}"
      name: "{{ ansible_operator_meta.name }}"
      namespace: "{{ ansible_operator_meta.namespace }}"
      conditions:
        - type: Pulp-API-Ready
          message: Missing Azure fields on Secret
          reason: MissingAzureFields
          status: "False"
          lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

  - name: Fail if required azure secret items are not present
    fail:
      msg: "Secret {{ object_storage_azure_secret  }} is missing required configuration data."

  when:
    - azure_secret_data_avaiable
    - not azure_account_name_available
    - not azure_account_key_available
    - not azure_container_available

- name: Store azure account name
  set_fact:
    azure_account_name: "{{ _custom_azure_configuration['resources'][0]['data']['azure-account-name'] | b64decode }}"

- name: Store azure account key
  set_fact:
    azure_account_key: "{{ _custom_azure_configuration['resources'][0]['data']['azure-account-key'] | b64decode }}"
  no_log: "{{ no_log }}"

- name: Store azure account container
  set_fact:
    azure_container: "{{ _custom_azure_configuration['resources'][0]['data']['azure-container'] | b64decode }}"

- name: Store azure account container path
  set_fact:
    object_storage_path: "{{ _custom_azure_configuration['resources'][0]['data']['azure-container-path'] | b64decode }}"
  when:
    - azure_secret_data_avaiable
    - _custom_azure_configuration.resources[0].data['azure-container-path'] is defined
    - _custom_azure_configuration.resources[0].data['azure-container-path'] | length

- name: Add azure connection string to azure settings
  set_fact:
    azure_connection_string_dict: "{'AZURE_CONNECTION_STRING': '{{ _custom_azure_configuration['resources'][0]['data']['azure-connection-string'] | b64decode }}' }"
  no_log: "{{ no_log }}"
  when:
    - azure_secret_data_avaiable
    - _custom_azure_configuration.resources[0].data['azure-connection-string'] is defined
    - _custom_azure_configuration.resources[0].data['azure-connection-string'] | length

- name: Add azure account name azure settings
  set_fact:
    azure_account_name_dict : "{'AZURE_ACCOUNT_NAME': '{{ azure_account_name }}' }"

- name: Add azure account key azure settings
  set_fact:
    azure_account_key_dict : "{'AZURE_ACCOUNT_KEY': '{{ azure_account_key }}' }"
  no_log: "{{ no_log }}"

- name: Add azure container azure settings
  set_fact:
    azure_container_dict : "{'AZURE_CONTAINER': '{{ azure_container }}' }"

- name: Add azure container path azure settings
  set_fact:
    azure_container_path_dict : "{'AZURE_LOCATION': '{{ object_storage_path }}' }"

- name: merge azure_account_name with settings
  set_fact:
    default_azure_settings: "{{ default_azure_settings|combine(azure_account_name_dict) }}"
  no_log: "{{ no_log }}"

- name: merge azure_account_key with settings
  set_fact:
    default_azure_settings: "{{ default_azure_settings|combine(azure_account_key_dict) }}"
  no_log: "{{ no_log }}"

- name: merge azure_container with settings
  set_fact:
    default_azure_settings: "{{ default_azure_settings|combine(azure_container_dict) }}"
  no_log: "{{ no_log }}"

- name: merge azure_container_path with settings
  set_fact:
    default_azure_settings: "{{ default_azure_settings|combine(azure_container_path_dict) }}"
  no_log: "{{ no_log }}"

- name: merge azure_connection_string with settings
  set_fact:
    default_azure_settings: "{{ default_azure_settings|combine(azure_connection_string_dict) }}"
  no_log: "{{ no_log }}"
  when:
    - azure_secret_data_avaiable
    - _custom_azure_configuration.resources[0].data['azure-connection-string'] is defined
    - _custom_azure_configuration.resources[0].data['azure-connection-string'] | length

- name: merge default_azure_settings with settings
  set_fact:
    default_settings: "{{ default_settings|combine(default_azure_settings) }}"
  no_log: "{{ no_log }}"
