---
- k8s_status:
    api_version: "{{ api_version }}"
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    conditions:
      - type: "{{ deployment_type|capitalize }}-API-Ready"
        message: Checking Ingress configurations
        reason: CheckingIngressConfigs
        status: "False"
        lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

- name: Set web protocol
  set_fact:
    web_protocol: "https"
  when:
    - ingress_tls_secret | length
    - route_tls_secret | length

- name: Set node address for ingress
  set_fact:
    content_origin: "{{ web_protocol }}://{{ hostname }}"
    ansible_api_hostname: "{{ web_protocol }}://{{ hostname }}"
    token_server: "{{ web_protocol }}://{{ hostname }}/token/"
  when:
    - ingress_type|lower == "ingress"
    - hostname is defined

- block:
  - k8s_status:
      api_version: "{{ api_version }}"
      kind: "{{ kind }}"
      name: "{{ ansible_operator_meta.name }}"
      namespace: "{{ ansible_operator_meta.namespace }}"
      conditions:
        - type: "{{ deployment_type|capitalize }}-API-Ready"
          message: Hostname is not defined when ingress is specified
          reason: HostnameNotDefined
          status: "False"
          lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

  - name: Fail if hostname is not defined when ingress is specified
    fail:
      msg: "The hostname must be specified when using ingress_type {{ ingress_type }}."

  when:
    - ingress_type|lower == "ingress"
    - hostname is not defined

- block:
    - name: Retrieve route URL
      k8s_info:
        kind: Route
        api_version: "route.openshift.io/v1"
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ ansible_operator_meta.name }}'
      register: route_url

    - name: Capture web URL
      set_fact:
        web_url: "https://{{ route_url['resources'][0]['status']['ingress'][0]['host'] }}"

  when: ingress_type | lower == 'route'


- name: Set node address for route
  set_fact:
    content_origin: "{{ web_url }}"
    ansible_api_hostname: "{{ web_url }}"
    token_server: "{{ web_url }}/token/"
  when:
    - ingress_type|lower == "route"

- block:
    - name: Retrieve service node port
      k8s_info:
        kind: Service
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ ansible_operator_meta.name }}-web-svc'
      register: web_service
      when:
        - nodeport_port is not defined

    - name: Store nodeport from service
      set_fact:
        nodeport_port: "{{ web_service['resources'][0]['spec']['ports'][0]['nodePort'] }}"
      when:
        - nodeport_port is not defined

    - name: DEBUG Show nodeport_port
      debug:
        msg: "{{ nodeport_port }}"

    - name: Retrieve web pod
      k8s_info:
        kind: Pod
        namespace: "{{ ansible_operator_meta.namespace }}"
        label_selectors:
          - "app.kubernetes.io/instance = nginx-{{ ansible_operator_meta.name }}"
      register: web_pod

    - name: Store node ip from pod ENV
      set_fact:
        node_ip: "{{ web_pod['resources'][0]['status']['hostIP'] }}"

    - name: DEBUG Show node_ip
      debug:
        msg: "{{ node_ip }}"

    - name: Set node address
      set_fact:
        content_origin: "http://{{ node_ip }}:{{ nodeport_port }}"
        ansible_api_hostname: "http://{{ node_ip }}:{{ nodeport_port }}"
        token_server: "http://{{ node_ip }}:{{ nodeport_port }}/token/"

  when:
    - ingress_type | lower == 'nodeport'

- name: Set svc.cluster.local address
  set_fact:
    content_origin: "http://{{ ansible_operator_meta.name }}-web-svc.{{ ansible_operator_meta.namespace }}.svc.cluster.local:24880"
    ansible_api_hostname: "http://{{ ansible_operator_meta.name }}-web-svc.{{ ansible_operator_meta.namespace }}.svc.cluster.local:24880"
    token_server: "http://{{ ansible_operator_meta.name }}-web-svc.{{ ansible_operator_meta.namespace }}.svc.cluster.local:24880/token/"
  when:
    - content_origin is not defined

- name: Set content_origin
  set_fact:
    content_origin_dict: "{ 'content_origin': '{{ content_origin }}', 'ansible_api_hostname': '{{ ansible_api_hostname }}', 'x_pulp_content_host': '{{ content_host }}', 'x_pulp_content_port': '{{ content_port }}' }"

- name: Set token_server and other container default settings
  set_fact:
    token_server_dict: "{ 'token_server': '{{ token_server }}', 'token_auth_disabled': 'False', 'token_signature_algorithm': 'ES256','public_key_path': '/etc/pulp/keys/container_auth_public_key.pem', 'private_key_path': '/etc/pulp/keys/container_auth_private_key.pem', 'galaxy_feature_flags': { 'execution_environments': 'True' }  }"
  when: container_token_secret is defined

- name: DEBUG Show content_origin_dict
  debug:
    msg: "{{ content_origin_dict }}"

- name: merge content_origin with settings
  set_fact:
    default_settings: "{{ default_settings|combine(content_origin_dict) }}"
  no_log: "{{ no_log }}"

- name: merge token_server with settings
  set_fact:
    default_settings: "{{ default_settings|combine(token_server_dict) }}"
  no_log: "{{ no_log }}"
  when: container_token_secret is defined

- name: DEBUG Show content_origin
  debug:
    msg: "{{ default_settings.content_origin }}"
