---
_redis_image: redis:latest

redis_resource_requirements:
  requests:
    cpu: 200m
    memory: 512Mi

# Here we use  _pulpproject_org_pulp to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_pulpproject_org_pulp']['spec'] }}"
