---
deployment_type: pulp

postgres_version: 12
postgres_image: postgres:12
postgres_resource_requirements:
  requests:
    storage: 8Gi
postgres_storage_class: ''
postgres_data_path: '/var/lib/postgresql/data/pgdata'

# Secret to lookup that provide the PostgreSQL configuration
postgres_configuration_secret: '{{ meta.name }}-postgres-configuration'


# Secret to lookup that provide the PostgreSQL configuration for old database
postgres_migrant_configuration_secret: ''

postgres_initdb_args: '--auth-host=scram-sha-256'
postgres_host_auth_method: 'scram-sha-256'

custom_resource_key: '_pulp_pulpproject_org_pulp'
database_status_present: false
