---
deployment_type: pulp

postgres_version: 12
_postgres_image: postgres:12

postgres_storage_requirements:
  requests:
    storage: 8Gi
postgres_resource_requirements: {}

postgres_data_path: '/var/lib/postgresql/data/pgdata'

# Secret to lookup that provide the PostgreSQL configuration
postgres_configuration_secret: '{{ ansible_operator_meta.name }}-postgres-configuration'


# Secret to lookup that provide the PostgreSQL configuration for old database
postgres_migrant_configuration_secret: ''

postgres_initdb_args: '--auth-host=scram-sha-256'
postgres_host_auth_method: 'scram-sha-256'

# Add a nodeSelector for the Postgres pods.
# It must match a node's labels for the pod to be scheduled on that node.
# Specify as literal block. E.g.:
# postgres_selector: |
#   disktype: ssd
#   kubernetes.io/arch: amd64
#   kubernetes.io/os: linux
postgres_selector: ''

# Add node tolerations for the Postgres pods.
# Specify as literal block. E.g.:
# postgres_tolerations: |
#   - key: "dedicated"
#     operator: "Equal"
#     value: "AutomationHub"
#     effect: "NoSchedule"
postgres_tolerations: ''

# Define postgres configuration arguments to use
postgres_extra_args: ''

custom_resource_key: '_automationhub_ansible_com_automationhub'
database_status_present: false

# Here we use  _automationhub_ansible_com_automationhub to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_automationhub_ansible_com_automationhub']['spec'] }}"
