---
deployment_type: pulp

postgres_version: 12
_postgres_image: postgres:12

postgres_storage_requirements:
  requests:
    storage: 8Gi
postgres_resource_requirements: {}

postgres_data_path: '/var/lib/postgresql/data/pgdata'

# Secret to lookup that provide the PostgreSQL configuration
postgres_configuration_secret: '{{ ansible_operator_meta.name }}-postgres-configuration'


# Secret to lookup that provide the PostgreSQL configuration for old database
postgres_migrant_configuration_secret: ''

postgres_initdb_args: '--auth-host=scram-sha-256'
postgres_host_auth_method: 'scram-sha-256'

custom_resource_key: '_pulp_pulpproject_org_pulp'
database_status_present: false

# Here we use  _pulp_pulpproject_org_pulp to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_pulp_pulpproject_org_pulp']['spec'] }}"
