---
# Required: specify name of pulp deployment to backup from
deployment_name: ''

# Specify a pre-created PVC (name) to backup to
backup_pvc: ''
backup_pvc_namespace: "{{ ansible_operator_meta.namespace }}"

# Size of backup PVC if created dynamically
backup_storage_requirements: ''

# Specify storage class to determine how to dynamically create PVC's with
backup_storage_class: ''

postgres_version: 13

# Secret Names
admin_password_secret: "{{ deployment_name }}-admin-password"
postgres_configuration_secret: "{{ deployment_name }}-postgres-configuration"

custom_resource_key: '_automationhub_ansible_com_automationhubbackup'

database_type: 'unmanaged'

azure_container_path: ''
