---
- hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core
    - operator_sdk.util
  vars:
    default_settings:
      cache_enabled: true
      db_encryption_key: "/etc/pulp/keys/database_fields.symmetric.key"
      galaxy_collection_signing_service: ansible-default
      ansible_certs_dir: "/etc/pulp/keys/"
      databases:
        default:
          HOST: "{{ postgres_host }}"
          ENGINE: django.db.backends.postgresql_psycopg2
          NAME: "{{ postgres_database }}"
          USER: "{{ postgres_user }}"
          PASSWORD: "{{ postgres_pass }}"
          PORT: "{{ postgres_port }}"
          CONN_MAX_AGE: 0
          OPTIONS:
            sslmode: '{{ postgres_sslmode }}'
      redis_host: "{{ ansible_operator_meta.name }}-redis-svc"
      redis_port: 6379
      redis_password: ""
    deployment_state: present
    _image: quay.io/pulp/pulp
    _image_version: stable
    _image_web: quay.io/pulp/pulp-web
    _image_web_version: stable
    image_pull_policy: IfNotPresent
    image_pull_secrets: []
    storage_type: File
    file_storage_access_mode: "ReadWriteMany"
    file_storage_size: "100Gi"
    raw_spec: "{{ vars['_automationhub_ansible_com_automationhub']['spec'] }}"
  roles:
    - postgres
    - pulp-web
    - pulp-routes
    - pulp-api
    - pulp-content
    - pulp-worker
    - pulp-status
